### ISSUE TITLE
能否支持http语音通话？

### ISSUE THREAD

**Issue by jiaxinonly** [VideoTogether/VideoTogether#106]
如果出于安全考虑，可以提示用户，让用户点击确认自行承担风险，而不是直接禁用，因为有很多小网站确实没有https，我了解到这个功能需要浏览器开启权限，我在chrome浏览器开启了http网站调用麦克风的权限，依然是无法使用的。另外是否能够像其他插件一样根据网站域名自动打开插件，或者用户手动将网站添加到插件使用列表里面，而不是全部网页都调用插件。

**Comment by maggch97** [comment]
1. 可以考虑
2. chrome 插件页面本身支持设置部分允许的网站, 但是绝对不推荐一般用户用这个功能

**Comment by jiaxinonly** [comment]
> 1. 可以考虑
> 2. chrome 插件页面本身支持设置部分允许的网站, 但是绝对不推荐一般用户用这个功能

手机端狐猴浏览器没有这个功能😂

**Comment by jiaxinonly** [comment]
> 1. 可以考虑
> 2. chrome 插件页面本身支持设置部分允许的网站, 但是绝对不推荐一般用户用这个功能

![image](https://github.com/VideoTogether/VideoTogether/assets/57223696/c62bb56e-9a73-4b4d-a977-e731218c914b)
关于第二个问题我设置了权限，但是必须得点击插件启用才能正常使用，当我启用后，再打开其他网站，插件也是会自动启动，没有实现特点的网站启动插件，是我设置不对吗？

**Comment by maggch97** [comment]
1. 不准备做了，因为需要用户设置，绝大部分用户不会设置。而且现在有了文字聊天功能，http网站可以降级用这个方式聊天
2. 狐猴我试了一下，这个功能是有用的。你试下或者给狐猴提bug吧

先close了
