### ISSUE TITLE
建议：全屏功能悬浮窗

### ISSUE THREAD

**Issue by altair441n** [VideoTogether/VideoTogether#113]
是否考虑在视频全屏状态下在屏幕右侧展示一个悬浮窗，点击唤出有发送文字和麦克风静音等功能。退出全屏发送文字有点不太方便。

**Comment by maggch97** [comment]
我觉得这个值得考虑做
但是现在有一些问题需要讨论
1. 遮挡问题，如何设计交互能够不遮挡视频的按钮
2. 还是使用现在的这样的窗口吗？还是单独设计一个小横条类似哔哩哔哩发弹幕的框框，尽量不遮挡视频
3. iOS上面无法做，iOS上苹果不允许除了视频以外的html元素全屏

**Comment by altair441n** [comment]
> 我觉得这个值得考虑做 但是现在有一些问题需要讨论
> 
> 1. 遮挡问题，如何设计交互能够不遮挡视频的按钮
> 2. 还是使用现在的这样的窗口吗？还是单独设计一个小横条类似哔哩哔哩发弹幕的框框，尽量不遮挡视频
> 3. iOS上面无法做，iOS上苹果不允许除了视频以外的html元素全屏

1. 有一个chrome插件[沉浸式翻译](https://github.com/immersive-translate/immersive-translate)，在移动浏览器右侧有半透明磁贴圆形悬浮窗，但是它全屏就不展示了，这个插件也是开源的，我不知道这个是否对你有帮助。
2. 感觉半透明的框框不错，其他弹幕网站和腾讯会议也是类似设计

**Comment by maggch97** [comment]
![image](https://github.com/VideoTogether/VideoTogether/assets/23057110/0b449246-1592-4703-8447-5cbf23694466)
