### ISSUE TITLE
请问“超级无敌牛的轻松分享”和“轻松分享”的区别是什么

### ISSUE THREAD

**Issue by altair441n** [VideoTogether/VideoTogether#121]
请问“超级无敌牛的轻松分享”和“轻松分享”的区别是什么，开启“超级无敌牛的轻松分享”后没发现有什么不同

**Comment by maggch97** [comment]
通过一些可能会影响视频正常播放的方式，增加轻松分享和视频下载的成功率

**Comment by altair441n** [comment]
那请问这个是否建议保持开启

**Comment by maggch97** [comment]
> 那请问这个是否建议保持开启

不建议，可能会在一些网站遇到没法播放视频的问题
