### ISSUE TITLE
关于文字聊天建议

### ISSUE THREAD

**Issue by cangming99** [VideoTogether/VideoTogether#123]
目前文字聊天没法看到具体的文字记录吗，如果多人的话，能否进入房间的时候自定义一个用户名，然后全局悬浮窗能够有相应的文字浮动或者弹幕

**Comment by maggch97** [comment]
超过97%的房间是双人房，多人房也只是3到4个人。没有计划实现这样的极少数需求

**Comment by cangming99** [comment]
那请问能否就是，发送文字消息后，悬浮框有相应的文字提醒，文字转语音有时候听不太清

**Comment by maggch97** [comment]
也没有，这个功能就是用来简单地交流的，语音聊天的替代

**Comment by cangming99** [comment]
好吧，期待以后某一天，祝您生活愉快
