### ISSUE TITLE
语音通话有回音

### ISSUE THREAD

**Issue by altair441n** [VideoTogether/VideoTogether#125]
最近语音通话时，偶现听到自己这边的回音，包括自己说话和视频播放的声音，对方听不见回音，关闭插件，重启浏览器也没解决。华为平板，鸿蒙系统，狐猴浏览器。

**Comment by maggch97** [comment]
安卓上浏览器应该都是走的系统的那一套回音消除，如果是偶尔听到那可能就是系统抽风了

**Comment by altair441n** [comment]
> 安卓上浏览器应该都是走的系统的那一套回音消除，如果是偶尔听到那可能就是系统抽风了

是偶现的，但不是一会儿好一会儿不好的，如果加入房间通话后有回音，那么基本就是一直有了，反之也是。
