### ISSUE TITLE
由于片源卡断导致的同步问题

### ISSUE THREAD

**Issue by yypyyds** [VideoTogether/VideoTogether#134]
观看人数：6人
浏览器：Edge, ipad safari
问题：好像是片源和观众的网络问题，有一方卡顿的时候，处理逻辑很奇怪，房主是暂停的，卡顿的成员正常出现加载进度条，但是**非卡顿成员会一直闪回**
建议：把其他成员的同步逻辑改为暂停

**Comment by maggch97** [comment]
感谢反馈，现在的逻辑应该只考虑了一人房主一人成员的情况，所以成员卡的时候会不暂停加载视频，之后如果有时间会改进一下

**Comment by maggch97** [comment]
现在有一个成员卡顿加载之后，会暂停其他所有成员和房主的视频

如果房主卡顿，会导致成员无限回播。这个是一直有的问题，新开了 https://github.com/VideoTogether/VideoTogether/issues/144 track这个问题

这个issue先关了

**Comment by maggch97** [comment]
修复会在这几天推送到所有人
