### ISSUE TITLE
建议加入倍速播放

### ISSUE THREAD

**Issue by whiteday13jin** [VideoTogether/VideoTogether#135]
插件很好用。奉上拙见，目前倍速播放无法使用，双方强制1倍速。建议加入倍速播放，将更为方便。或直接嵌入如图类似的html5播放器增强，提供倍速播放乃至更多进阶功能
![image](https://github.com/VideoTogether/VideoTogether/assets/113036420/fd692f64-ee0b-4dbf-887e-c0f008f0d437)

**Comment by maggch97** [comment]
没看懂，现在房主那边改了倍数的话是会同步到其他人那边
