### ISSUE TITLE
疑似会导致cloudflare的人机验证失败

### ISSUE THREAD

**Issue by Kshot27** [VideoTogether/VideoTogether#150]
![feb7f690d4745fc57a528404994c97b](https://github.com/user-attachments/assets/9e103b73-c7f5-4a38-9591-e321b0194b29)
近期谷歌和edge浏览器在插件开启的情况下会过不去cf的人机验证，不确定是电脑原因还是插件原因。

**Comment by maggch97** [comment]
我也遇到了，可能是cf更新了什么策略，得研究下

**Comment by RuioWolf** [comment]
+1, 首先使用 `--disable-extensions` 启动 Chrome 测试正常，后面逐一排查插件，禁用 VideoTogether 插件后正常。

**Comment by maggch97** [comment]
![image](https://github.com/user-attachments/assets/91349b40-094c-4f4f-9e19-c521cd0291e3)

破案了，之前为了适配百度网盘做的覆写shadowroot，出了问题

**Comment by maggch97** [comment]
![image](https://github.com/user-attachments/assets/0169818f-a40d-4a04-aca9-b16e0723d138)

推了一个热更新，需要在设置界面手动点一下检查更新

现在百度网盘已经不依赖这段代码了，下个商店版本考虑把他删掉了

**Comment by maggch97** [comment]
![image](https://github.com/user-attachments/assets/75945eb0-3364-4e82-83d6-c5376d57d330)

**Comment by maggch97** [comment]
因为现在推送都走 jsdelivr, 所以可能要隔一天才能推出去

**Comment by Kshot27** [comment]
> 因为现在推送都走 jsdelivr, 所以可能要隔一天才能推出去

感谢

**Comment by maggch97** [comment]
最新的3.0.11已经彻底修复这个问题

**Comment by maggch97** [comment]
iOS可能还有这个问题，影响比较小，之后再看看
