### ISSUE TITLE
YouTube 无法使用

### ISSUE THREAD

**Issue by castsoma** [VideoTogether/VideoTogether#152]
大概是从昨天发现的(8月8日)，在其他页面都正常，在 YouTube 时右下角会闪一下 Loading 然后就不见了。
控制台报错为：
This document requires 'TrustedHTML' assignment. :chrome.js:1307
Uncaught 
TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.   :chrome.js:4284 

在其他页面不会报错，比如 bilibili，或者非视频的 hotmail github 等等，目前在我常用的页面中只有 YouTube 有这个情况。
浏览器是 Edge 127.0.2651.86 (正式版本) (64 位)

7日晚上还在用。然后8日遇到了 cloud flare 的验证问题，在插件设置页面中点击了更新版本，当时没印象有没有问题，之后晚上看视频时发现有这个问题。卸载了重新从微软商店安装，也还是这样。到目前为止 YouTube 都无法使用。

在无痕模式中只启用这一个扩展也是这样。好像不是扩展之间冲突。

**Comment by maggch97** [comment]
cloudflare已经热更新修复了。youtube的问题要更新最新的商店版本，也已经修复了。最新的商店版本是3.0.10

你试试更新完了，如果没有问题反馈一下，我就把这个关了

**Comment by maggch97** [comment]
cloudflare 的问题我看了下，现在只修复了cloudflare.com这个域名，有一些是在自己域名上的。
这个不准备发热更新解决了，会发一个商店版本

YouTube最新的商店版本应该是没问题的

**Comment by castsoma** [comment]
已经可以了，可以关了，感谢大佬。
