### ISSUE TITLE
导致Cloudflare无限验证

### ISSUE THREAD

**Issue by SnowArk** [VideoTogether/VideoTogether#155]
启用插件后，无法通过Cloudflare的认证，会无限刷新，测试了多个Cloudflare保护的网站都是这样

**Comment by maggch97** [comment]
iOS还是其他平台

**Comment by maggch97** [comment]
> > iOS还是其他平台
> 
> Windows Chrome最新版，已测试在无痕模式下单独启用VideoTogether插件，导致Cloudflare验证过不去。 测试网站：https://steamdb.info/

你的插件是最新的吗，什么版本，这个问题在chrome和edge最新插件上都修好了

**Comment by maggch97** [comment]
> > > > iOS还是其他平台
> > > 
> > > 
> > > Windows Chrome最新版，已测试在无痕模式下单独启用VideoTogether插件，导致Cloudflare验证过不去。 测试网站：https://steamdb.info/
> > 
> > 
> > 你的插件是最新的吗，什么版本，这个问题在chrome和edge最新插件上都修好了
> 
> 是最新的呀，3.0.11，也点过插件管理页面的检查更新了

好的我这两天研究下是哪里冲突了，cloudflare最近一直在改这个验证

**Comment by maggch97** [comment]
chrome和edge插件推了一个热更新解决了，大概要延迟一天推送到所有人。

iOS 没法热更新，暂时无法解决，看看cloudflare会不会修
