### ISSUE TITLE
功能请求：进度双向同步

### ISSUE THREAD

**Issue by BecodReyes** [VideoTogether/VideoTogether#32]
提供一个仅能由房主控制的开关，用于进度双向同步
即为 `任意一端均可控制对方播放状态`

方案参考：[LouisYLWang/Sync-Sofa](https://github.com/LouisYLWang/Sync-Sofa)

**Comment by maggch97** [comment]
你好，能描述一下使用场景吗，因为我暂时不清楚这种使用场景是什么

**Comment by maggch97** [comment]
不会支持双向/多向同步，这会导致我们依赖player的play,pause等事件。并且还会让服务端视频状态维护变得困难。
