### ISSUE TITLE
建议增加选择音轨和字幕的功能

### ISSUE THREAD

**Issue by wjb00** [VideoTogether/VideoTogether#4]
异地播放mkv本地视频时，无法选择音轨和字幕，有点小遗憾，希望能增加该功能，谢谢！

**Comment by maggch97** [comment]
之后给vlc添加支持可能是更好的解决方法。因为网页播放视频有很多限制，依赖浏览器实现，比如h265大部分放不了

**Comment by xuminxi** [comment]
很实用的项目，本地server已经建好了，蹲一个播放器 release 版本

**Comment by xuminxi** [comment]
> 很实用的项目，本地server已经建好了，蹲一个播放器 release 版本

Star 给了

**Comment by maggch97** [comment]
> > 很实用的项目，本地server已经建好了，蹲一个播放器 release 版本
> 
> Star 给了

https://syncplay.pl/ 之后不会做本地播放器的支持了，syncplayer对本视播放器的支持已经非常完善了
