### ISSUE TITLE
支持 websocket

### ISSUE THREAD

**Issue by maggch97** [VideoTogether/VideoTogether#40]
现在2秒的轮询会导致进度同步大概延迟两三秒。如果我们能在轮询的基础上通过websocket 触发同步事件，体验会有一些提升

**Comment by dcb9** [comment]
目前这个有进展吗？我可以开发 Go Server，但目前对整套系统的运行规则并不清楚，可以先出一个简单的 API 文档，列出 Client 与 Server 之间需要交换哪些数据，然后服务端应该对这些数据做什么操作。

**Comment by maggch97** [comment]
> 目前这个有进展吗？我可以开发 Go Server，但目前对整套系统的运行规则并不清楚，可以先出一个简单的 API 文档，列出 Client 与 Server 之间需要交换哪些数据，然后服务端应该对这些数据做什么操作。

get 和 update 是现在最高频的操作（2秒一次），如果要做第一阶段可以替换着两个接口

ws 接收 update 数据，如果 update 数据中的 url，paused 等字段改变了就要向房间其他成员推送，currentTime 是否修改需要写一段逻辑来比较，因为视频播放currentTime就是一直在改变的

ws 接口应该和现在的 http 接口完全兼容，也就是 http 用户和 ws 用户能一起看。短期无法完全抛弃 http
1. 插件的热更新无法 100% 成功
2. tampermonkey 脚本，chrome插件都对 http 请求做了很多兜底代码应对 http 请求发不出去的情况，ws 这一块的逻辑还是缺失的
3. 现在用的中国 cdn 不支持 ws，如果检测到用户无法访问国外服务器，会切到中国cdn

kraken 这个接口暂时不要动它
1. 这只是 https://github.com/MixinNetwork/kraken 这个语音通话项目的反代，原项目就是周期性的 http 请求
2. 语音通话用户才会使用这个接口，只有5%到10%的用户使用语音功能

**Comment by dcb9** [comment]
> ws 接收 update 数据，如果 update 数据中的 url，paused 等字段改变了就要向房间其他成员推送，currentTime 是否修改需要写一段逻辑来比较，因为视频播放currentTime就是一直在改变的

我感觉 server 先不做关于 currentTime 逻辑相关的处理，收到 update 之后就 push 给所有的成员（除了自己），这样逻辑跟原来的两个接口 update 和 get 就完全一致了。

另外哪些成员会做 update 操作，哪些成员做 get 操作啊？

**Comment by maggch97** [comment]
> > ws 接收 update 数据，如果 update 数据中的 url，paused 等字段改变了就要向房间其他成员推送，currentTime 是否修改需要写一段逻辑来比较，因为视频播放currentTime就是一直在改变的
> 
> 我感觉 server 先不做关于 currentTime 逻辑相关的处理，收到 update 之后就 push 给所有的成员（除了自己），这样逻辑跟原来的两个接口 update 和 get 就完全一致了。
> 
> 另外哪些成员会做 update 操作，哪些成员做 get 操作啊？

只有房主 update，其他所有人 get

**Comment by maggch97** [comment]
还有一个点是，update有一个tempuser的参数，每次用户点击创建的时候会生成一个新的uuid作为tempuser。要保证只有最新的tempuser能够同步成功，其他都需要失败。否则会出现多个房主的问题

**Comment by dcb9** [comment]
> 还有一个点是，update有一个tempuser的参数，每次用户点击创建的时候会生成一个新的uuid作为tempuser。要保证只有最新的tempuser能够同步成功，其他都需要失败。否则会出现多个房主的问题

那就是一个 Room 只有一位 Host，有多位 Guest，其中只有 Host 可以更新 Room 数据。

HTTP 接口 

- Host 调用 room/update 接口若无该房间则添加房间，并将当前创建者设置为 Host，若已创建则更新房间信息
- Guest 调用 room/get 接口获取最新的房间数据

WebSocket 接口 

WebSocket 消息使用 JSON 格式，最外层为 {"path": "/room/update", "data": <Request/Response Data> }

- Host 调用 /room/update 后将房间最新数据广播到房间的 Guests
- Guest 调用 /room/join 订阅房间的最新数据

**Comment by maggch97** [comment]
> > 还有一个点是，update有一个tempuser的参数，每次用户点击创建的时候会生成一个新的uuid作为tempuser。要保证只有最新的tempuser能够同步成功，其他都需要失败。否则会出现多个房主的问题
> 
> 那就是一个 Room 只有一位 Host，有多位 Guest，其中只有 Host 可以更新 Room 数据。
> 
> HTTP 接口
> 
> * Host 调用 room/update 接口若无该房间则添加房间，并将当前创建者设置为 Host，若已创建则更新房间信息
> * Guest 调用 room/get 接口获取最新的房间数据
> 
> WebSocket 接口
> 
> WebSocket 消息使用 JSON 格式，最外层为 {"path": "/room/update", "data": <Request/Response Data> }
> 
> * Host 调用 /room/update 后将房间最新数据广播到房间的 Guests
> * Guest 调用 /room/join 订阅房间的最新数据

好，接口进了，js那块我来写就行

**Comment by maggch97** [comment]
0.3.79 fixed
