### ISSUE TITLE
[建议] 把这个issue模板给删了，好难用

### ISSUE THREAD

**Issue by maggch97** [VideoTogether/VideoTogether#44]
### 描述功能请求

[建议] 把这个issue模板给删了，好难用

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [ ] 用户体验
- [ ] 测试和发布
- [ ] 新的扩展
- [ ] 其他

**Comment by valetzx** [comment]
来自 PR https://github.com/VideoTogether/VideoTogether/pull/42 已删
