### ISSUE TITLE
在ios端语音通话问题

### ISSUE THREAD

**Issue by dxq1312064669** [VideoTogether/VideoTogether#72]
1.在ios端进行通话时无法分别调节通话和视频音量 因此会导致通话声音比视频声音大的问题
2.希望作者添加关闭通话的按键
3.可能是自己设备的问题 在通话过程中会听到自己的声音和对方设备正在播放的声音（对方戴着耳机）

**Comment by maggch97** [comment]
后续会改进

**Comment by maggch97** [comment]
2. 已经增加了麦克风静音按钮
3. 网页上只能使用浏览器提供的回声消除，降噪功能，增加了一个开启关闭通话降噪的按钮

**Comment by maggch97** [comment]
1. iOS 网页上所有的音视频都只能使用系统音量播放，没有办法单独调节音量
