### ISSUE TITLE
部署不支持ipv6吗？

### ISSUE THREAD

**Issue by qiurigao** [VideoTogether/VideoTogether#73]
* Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.127:5000
 
ipv4访问正常，ipv6提示拒绝连接，防火墙没问题

**Comment by maggch97** [comment]
https://github.com/VideoTogether/VideoTogether/blob/main/release/extension.user.js#L336 改成修改后的 vt.user.js 位置
https://github.com/VideoTogether/VideoTogether/blob/main/release/vt.user.js#L623 改成 api 的 host

主要要改这两个位置，而且 api 需要是 https 的。

私有化部署文档年久失修了

**Comment by maggch97** [comment]
暂时不准备投入到私有化部署相关的工作里面
