### ISSUE TITLE
设置无法保存

### ISSUE THREAD

**Issue by MonicaWQY** [VideoTogether/VideoTogether#74]
设置界面勾选了窗口默认最小化选项，但重新打开设置界面的时候不是勾选状态。

**Comment by maggch97** [comment]
什么设备，这么安装的，设置页面的链接发一下

**Comment by MonicaWQY** [comment]
PC，Win10，Edge扩展商店，https://setting.2gether.video/v2.html


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VideoTogether/VideoTogether"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月5日(星期三) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VideoTogether/VideoTogether] 设置无法保存 (Issue #74)





 
什么设备，这么安装的，设置页面的链接发一下

**Comment by maggch97** [comment]
能在设置页面 F12 打开控制台,然后点几下开关看看有没有报错吗. 我本地没法复现

**Comment by MonicaWQY** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VideoTogether/VideoTogether"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 晚上10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VideoTogether/VideoTogether] 设置无法保存 (Issue #74)





 
能在设置页面 F12 打开控制台,然后点几下开关看看有没有报错吗. 我本地没法复现

**Comment by maggch97** [comment]
你是不是把插件的站点访问权限给改了, 如果插件没有在设置页面运行的话, 设置是不会生效的

**Comment by MonicaWQY** [comment]
&nbsp; &nbsp; &nbsp; 原来是这样，我明白了，谢谢！
&nbsp; &nbsp; &nbsp; 但是还有个问题，就是我改回站点访问权限让插件在设置页面运行之后，设置界面如下图可以保存了，但如果我在关闭视频页面
的时候插件右下角窗口不是最小化的，我再次进入视频页面，右下角就会是窗口，而不是最小化。&nbsp; &nbsp; &nbsp; 我以为的这条设置选项应该的功能是：不论我自己有没有点击右下角小图标让窗口显示出来，我关闭页面再次打开的时候它都是最小化状态。
&nbsp; &nbsp; &nbsp; 谢谢！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VideoTogether/VideoTogether"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VideoTogether/VideoTogether] 设置无法保存 (Issue #74)





 
你是不是把插件的站点访问权限给改了, 如果插件没有在设置页面运行的话, 设置是不会生效的

**Comment by maggch97** [comment]
原因是现在还有一个功能是如果手动打开窗口，默认的设置就不生效了。会记住在每个网站上窗口上次的状态。

先关掉这个issue了

**Comment by MonicaWQY** [comment]
好的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VideoTogether/VideoTogether"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 凌晨0:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VideoTogether/VideoTogether] 设置无法保存 (Issue #74)





 
原因是现在还有一个功能是如果手动打开窗口，默认的设置就不生效了。会记住在每个网站上窗口上次的状态。
 
先关掉这个issue了
