### ISSUE TITLE
Websockt 后, 没有了周期性校准事件的功能

### ISSUE THREAD

**Issue by maggch97** [VideoTogether/VideoTogether#87]
之前两秒会校准一次时间

**Comment by dcb9** [comment]
原来是每个 guest 自己每隔一段时间执行 /room/get 操作来完成该功能？

**Comment by maggch97** [comment]
> 原来是每个 guest 每隔一段时间执行 /room/get 操作来完成该功能？

之前的每个接口返回中有一个 timestamp 字段是当前服务器的时间，插件的逻辑是 请求开始和结束的本地时间取平均 和接口返回的 timestamp 做差就能计算出本地时间和服务器时间的差

校时的目的时每台设备时间都是不准的

这个计算方法理论上请求花费时间越短越准，切到 ws 之后，只有调用一次 /timestamp 接口对时了。按照之前的经验，有些网络下一个请求可能会花费超过 5 秒

不过问题不大，99%的情况下不会有问题
